### ISSUE TITLE
Logging, but unable to reset to re-calibrate

### ISSUE THREAD

**Issue by micko247** [cherryphilip74/iSpindel-PCB#13]
Hi, I have recently built two units (v3.2) & both are logging. (I actually had a number of issues, have built 10, especially with the temp logging, but I’ll leave that for another post).
I believe I got something wrong with the calibration as the SG stays at 1.004 regardless of the tilt. I use brewfather to log via http. I had no problems accessing configuration until now after they’ve started logging. I cannot access the config even though the wemos does rest and try to open an access point but it logs out. 

Thanks in advance, Mick

**Comment by cswelin** [comment]
Append [SG] to the name, since it’s reporting in SG BF requires [SG] in the name.

**Comment by micko247** [comment]
Thanks cswelin, do you mean the name of the spindle? Mine are Red and Blue. Do you have a link that describes this? Thanks

**Comment by cswelin** [comment]
@micko247 

Correct, in the ispindel configuration, so you’d namw yours Red[SG] and Blue[SG]. I’ve never had luck putting it as a prefix (would still report 1.004), only suffix.  Here’s the doc explanation it https://docs.brewfather.app/integrations/ispindel

**Comment by micko247** [comment]
Great thanks. Unfortunately I can’t access configuration. I may try re-loading the firmware. Thanks

**Comment by cswelin** [comment]
You should be able to reset to config mode by shorting the two holes on the top of the PCB a couple times In row. (on the part that sticks out)

**Comment by micko247** [comment]
I don’t think the v3.2 has this. The reset on the wemos does work, the light starts blinking, and it establishes an access point I can connect to on my computer. But it doesn’t connect successfully. I’ve tried several times on both units.

**Comment by cswelin** [comment]
Right, 
Does it connect to the access point but not load the captive portal? if so, try going to `192.168.4.1` in the browser

**Comment by micko247** [comment]
Correct, and I’ve tried 192.168.4.1

**Comment by micko247** [comment]
Ahhh, now I see the bit about Plato & SG. I’d missed that bit. Cheers

**Comment by micko247** [comment]
Specific issue fixed, for some reason Chrome went offline.
