### ISSUE TITLE
jlcpcb.com doesn't match some parts

### ISSUE THREAD

**Issue by rackam74** [cherryphilip74/iSpindel-PCB#15]
Hi, I think the BOM/CPL aren't uptodate with jlcpcb.com, isn't it??

![Screenshot_2020-01-03 PCB Prototype PCB Fabrication Manufacturer - JLCPCB](https://user-images.githubusercontent.com/59316064/71749803-c38c6c80-2e76-11ea-878e-a124347bd764.png)

**Comment by rackam74** [comment]
I've tried again, and it's ok!

**Comment by cherryphilip74** [comment]
Ok, thanks

Il Sab 4 Gen 2020, 19:25 rackam74 <notifications@github.com> ha scritto:
