### ISSUE TITLE
Reply to your last email

### ISSUE THREAD

**Issue by jhwerner1** [cherryphilip74/iSpindel-PCB#17]
**[Your Quote]()** "After flashing pls you solder the Wemos on pcb... i don't know what is the
issue."

**The issue is...**
After re-installing the Wemos, I still cannot get it to set an access point, cannot re-flash with NODEMCU, logs said "Finding device", never finds.

Followed your Technical Details/ Components instructions to the letter.

Question: Concerning https://jlcpcb.com, when I ordered, they show  images of SMD board with 
Original part placement and  Corrected Part Placement. 

They rotated the D1 Diode 180 degrees, they also rotated the IC2 & IC2 components 90 degrees on the corrected part placement image. Is this causing my issues? If it is how due I prevent them from making changes?

Joe

**Comment by cherryphilip74** [comment]
could you send me the DFM analysis that can you find inside to order
history? I want to check if jlcpcb provided to correction or not. The
preview is not real.



Thanks
Filippo

Il Mer 15 Gen 2020, 17:39 jhwerner1 <notifications@github.com> ha scritto:

**Comment by cherryphilip74** [comment]
Hi @jhwerner1 ,
here a screenshot of layout
![image](https://user-images.githubusercontent.com/19619650/72462948-8ad38800-37d2-11ea-8d1a-f752c21a62f0.png)
All devices are in correct position, but i want to understand the real issue.
Could you send me some pics of the pcb? Where are you live? We can organize a pickup for shipment at my attention
Thanks and Regards
Filippo

**Comment by jhwerner1** [comment]
I copied and pasted the images from the DFM Analysis attached to this email. 

Original Parts Placement
![image](https://user-images.githubusercontent.com/42916097/72474306-813c2700-37b6-11ea-8b0f-87a00a44451b.png) 

Actual Parts Placement 
![image](https://user-images.githubusercontent.com/42916097/72474338-95802400-37b6-11ea-8042-c0265566479b.png) 







Original parts             Actual Placement
placement

**Comment by cherryphilip74** [comment]
The actual placement is correct.

**Comment by jhwerner1** [comment]
Is this suggestion from an earlier post correct?

Quote "You might want to try to manually force GPIO0 (pin D3 on the board)
low (this initiates firmware upload mode) after reset of the Wemos.

   - Remove USB
   - Connect D3 to GND
   - Plug-in USB
   - Try upload in firmware.
   - disconnect D3 from GND"
