### ISSUE TITLE
Tips for de-solder MPU-6050

### ISSUE THREAD

**Issue by Naesstrom** [cherryphilip74/iSpindel-PCB#21]
So I have a bunch of v4's with none working Gyros that I need to desolder, any hints on how to remove them without damaging the gyro or the pcb! I was dumb enough to cut the pins on them before noticing that they didn't work so can't pull on them with pliers while heating!

**Comment by rjaakke** [comment]
Use a desoldering pump, they are cheap  on eBay and AliExpress

**Comment by Naesstrom** [comment]
Bought a dremel versatip, used the brad flame adapter and they came right off!
