### ISSUE TITLE
No link or file

### ISSUE THREAD

**Issue by DrBabbage** [cherryphilip74/iSpindel-PCB#23]
Hey there, I dropped you a donation. Would it be possible for you send me the gerber files?
I would also love to have a BOM. 
Nice project!

**Comment by cherryphilip74** [comment]
Thanks a lot for donation.Im out of house, when I'll come back I will send you gerber files or you can also order pcb on pcbway.com (shared projects)Il 22 Lug 2020 19:28, DrBabbage <notifications@github.com> ha scritto:
Hey there, I dropped you a donation. Would it be possible for you send me the gerber files?
I would also love to have a BOM.
Nice project!

**Comment by DrBabbage** [comment]
Thank you SO much!
Will order them from jlcpcb so a gerber file would be awesome.
Do you know roughly when you are home again?
Don't stress yourself, I am working at a hospital and thanks to corona I have no time to do anything but working for at least 2 months.

**Comment by DrBabbage** [comment]
hey, short question are you at home again?
Thank you so much!

**Comment by cherryphilip74** [comment]
No! I'll come back after the Aug 17th.FilippoIl 11 Ago 2020 18:29, DrBabbage <notifications@github.com> ha scritto:
hey, short question are you at home again?
Thank you so much!

**Comment by DrBabbage** [comment]
Could you send me the file ? :)
Thanks!

**Comment by DrBabbage** [comment]
Sorry I have seen only now that you made a new commit. Thank you :)
