### ISSUE TITLE
PCB 31mm Wide?

### ISSUE THREAD

**Issue by enorfelt** [cherryphilip74/iSpindel-PCB#27]
Just received my boards from pcbway. When I ordered them I saw that they where 31mm wide. Is that correct? They feel kind of loose in an XL petling with 33mm inner dimension.

Thx!

**Comment by ljruiten** [comment]
I have this exact same problem, did you manage to find a good workaround? The PCB not moving inside the tube is kind of key to the working of this device..

**Comment by cherryphilip74** [comment]
I'm sorry,  you can use a scotch tape on top of battery.Il 14 Apr 2021 20:05, ljruiten ***@***.***> ha scritto:
I have this exact same problem, did you manage to find a good workaround? The PCB not moving inside the tube is kind of key to the working of this device..

**Comment by ljruiten** [comment]
@enorfelt actually after further investigation this is not an issue... You have to realize that in the perfect situation the ispindel should have three contact points with the casing: either side of the PCB, and the battery...
Therefore the PCB is not centered in the casing, it is lowered, get it? I just added the battery holder and the battery and could not even fit the PCB in the case, had to sand down the sides of the PCB which now has a perfect fit with the case.

**Comment by enorfelt** [comment]
> @enorfelt actually after further investigation this is not an issue... You have to realize that in the perfect situation the ispindel should have three contact points with the casing: either side of the PCB, and the battery...
> Therefore the PCB is not centered in the casing, it is lowered, get it? I just added the battery holder and the battery and could not even fit the PCB in the case, had to sand down the sides of the PCB which now has a perfect fit with the case.

That makes perfect sense! Thank you 😊
